spring.application.name=gym-api

spring.datasource.url=jdbc:h2:mem:gymdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

spring.h2.console.enabled=true

spring.jackson.serialization.write-dates-as-timestamps=false

jwt.secret=${JWT_SECRET:c29tZVZlcnlMb25nU2VjcmV0S2V5VGhhdElzQXRMZWFzdDI1NkJpdHNMb25n}
